//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp_Jobs.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Job
    {
        public int Job1 { get; set; }

        [DisplayName("Job Title")]
        [Required(ErrorMessage = "Job requires a title.")]
        public string JobTitle { get; set; }

        [DisplayName("Description")]
        [Required(ErrorMessage = "You must provide a description for this job.")]
        public string JobDescription { get; set; }
        
        [DisplayName("Created At")]
        [Required(ErrorMessage = "You must provide an creation date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> CreatedAt { get; set; }

        [DisplayName("Expires At")]
        [Required(ErrorMessage = "You must provide an expiration date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public Nullable<System.DateTime> ExpiresAt { get; set; }
    }
}
